version: "2"
services:
  ros_melodic:
    image: l4t-ros:32.5.0-ros_melodic
    container_name: lidar_ros
    network_mode: "host"
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: /home/taku9/docker_ws/data
        target: /workspace/docker_bind_Local
      # - type: bind
      #   source: /media/taku9/SSD_2TB
      #   target: /workspace/docker_bind_SSD
      - type: bind
        source: /run/jtop.sock
        target: /run/jtop.sock
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

